#pragma once

#include "order_book.hpp"
#include "risk_management.hpp"

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <iomanip>
#include <map>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

struct SymbolPnlState {
    SymbolId symbol_id{DefaultSymbol};

    Position position{0};

    /*
        Average price of the currently open position.

        If position is zero, this is zero.
    */
    long double average_entry_price{0.0L};

    long double realised_pnl{0.0L};

    /*
        Cash generated by this symbol.

        Buys reduce cash.
        Sells increase cash.
    */
    long double net_cash_flow{0.0L};

    std::uint64_t bought_quantity{0};
    std::uint64_t sold_quantity{0};

    long double gross_buy_notional{0.0L};
    long double gross_sell_notional{0.0L};

    std::uint64_t fill_count{0};
};

struct AccountPnlState {
    ParticipantId participant_id{
        UnknownParticipant
    };

    long double initial_cash{0.0L};
    long double cash_balance{0.0L};

    std::map<SymbolId, SymbolPnlState>
        symbols;
};

struct PnlProcessingStatistics {
    std::uint64_t trades_processed{0};
    std::uint64_t trades_rejected{0};
    std::uint64_t participant_fills_applied{0};
};

struct PnlReportConfig {
    /*
        Use 100 when Price is stored in pence and you
        want the report displayed in pounds.

        Use 1 when Price represents generic ticks.
    */
    long double monetary_scale{1.0L};

    std::string currency_prefix{};

    int decimal_places{2};
};

class PnlEngine {
public:
    void registerAccount(
        ParticipantId participantId,
        long double initialCash = 0.0L
    ) {
        if (participantId == UnknownParticipant) {
            throw std::invalid_argument(
                "Participant ID zero is reserved for unknown participants"
            );
        }

        auto [iterator, inserted] =
            accounts_.try_emplace(
                participantId,
                AccountPnlState{
                    participantId,
                    initialCash,
                    initialCash,
                    {}
                }
            );

        if (!inserted) {
            throw std::invalid_argument(
                "Participant account is already registered"
            );
        }
    }

    bool containsAccount(
        ParticipantId participantId
    ) const {
        return accounts_.contains(participantId);
    }

    /*
        Processes only trades that have not previously
        been processed from this trade-history vector.
    */
    bool processNewTrades(
        const std::vector<Trade>& trades
    ) {
        if (
            processed_trade_count_ >
            trades.size()
        ) {
            processing_errors_.push_back(
                "Trade history became shorter. "
                "Call PnlEngine::reset() after resetOrderBook()."
            );

            return false;
        }

        while (
            processed_trade_count_ <
            trades.size()
        ) {
            processTrade(
                trades[processed_trade_count_]
            );

            ++processed_trade_count_;
        }

        return true;
    }

    bool processTrade(const Trade& trade) {
        if (
            trade.price <= 0 ||
            trade.quantity == 0 ||
            trade.symbol_id == 0
        ) {
            ++statistics_.trades_rejected;

            processing_errors_.push_back(
                "Rejected invalid trade: maker order " +
                std::to_string(trade.maker_order_id) +
                ", taker order " +
                std::to_string(trade.taker_order_id)
            );

            return false;
        }

        /*
            The aggressor is the incoming/taker order.

            Therefore the maker is always on the
            opposite side.
        */
        Side makerSide =
            trade.aggressor_side == Side::Buy
                ? Side::Sell
                : Side::Buy;

        Side takerSide =
            trade.aggressor_side;

        if (
            trade.maker_participant_id !=
            UnknownParticipant
        ) {
            applyFill(
                trade.maker_participant_id,
                trade.symbol_id,
                makerSide,
                trade.price,
                trade.quantity
            );

            ++statistics_
                .participant_fills_applied;
        }

        if (
            trade.taker_participant_id !=
            UnknownParticipant
        ) {
            applyFill(
                trade.taker_participant_id,
                trade.symbol_id,
                takerSide,
                trade.price,
                trade.quantity
            );

            ++statistics_
                .participant_fills_applied;
        }

        ++statistics_.trades_processed;

        return true;
    }

    bool setMarkPrice(
        SymbolId symbolId,
        long double markPrice
    ) {
        if (
            symbolId == 0 ||
            markPrice <= 0.0L
        ) {
            return false;
        }

        mark_prices_[symbolId] = markPrice;
        return true;
    }

    /*
        Uses the current order book midpoint as the mark.

        If only one side exists, it uses that side's price.
    */
    bool markFromCurrentOrderBook(
        SymbolId symbolId = DefaultSymbol
    ) {
        std::optional<Price> currentBid =
            bestBid();

        std::optional<Price> currentAsk =
            bestAsk();

        if (
            currentBid.has_value() &&
            currentAsk.has_value()
        ) {
            long double midpoint =
                (
                    static_cast<long double>(
                        currentBid.value()
                    ) +
                    static_cast<long double>(
                        currentAsk.value()
                    )
                ) /
                2.0L;

            return setMarkPrice(
                symbolId,
                midpoint
            );
        }

        if (currentBid.has_value()) {
            return setMarkPrice(
                symbolId,
                static_cast<long double>(
                    currentBid.value()
                )
            );
        }

        if (currentAsk.has_value()) {
            return setMarkPrice(
                symbolId,
                static_cast<long double>(
                    currentAsk.value()
                )
            );
        }

        return false;
    }

    std::optional<long double> markPrice(
        SymbolId symbolId
    ) const {
        auto iterator =
            mark_prices_.find(symbolId);

        if (iterator == mark_prices_.end()) {
            return std::nullopt;
        }

        return iterator->second;
    }

    const AccountPnlState* findAccount(
        ParticipantId participantId
    ) const {
        auto iterator =
            accounts_.find(participantId);

        if (iterator == accounts_.end()) {
            return nullptr;
        }

        return &iterator->second;
    }

    const SymbolPnlState* findSymbol(
        ParticipantId participantId,
        SymbolId symbolId
    ) const {
        const AccountPnlState* account =
            findAccount(participantId);

        if (account == nullptr) {
            return nullptr;
        }

        auto iterator =
            account->symbols.find(symbolId);

        if (iterator == account->symbols.end()) {
            return nullptr;
        }

        return &iterator->second;
    }

    long double unrealisedPnl(
        ParticipantId participantId,
        SymbolId symbolId
    ) const {
        const SymbolPnlState* state =
            findSymbol(
                participantId,
                symbolId
            );

        if (state == nullptr) {
            return 0.0L;
        }

        auto markIterator =
            mark_prices_.find(symbolId);

        if (markIterator == mark_prices_.end()) {
            return 0.0L;
        }

        return calculateUnrealisedPnl(
            *state,
            markIterator->second
        );
    }

    long double realisedPnl(
        ParticipantId participantId
    ) const {
        const AccountPnlState* account =
            findAccount(participantId);

        if (account == nullptr) {
            return 0.0L;
        }

        long double total = 0.0L;

        for (
            const auto& [symbolId, state] :
            account->symbols
        ) {
            static_cast<void>(symbolId);
            total += state.realised_pnl;
        }

        return total;
    }

    long double unrealisedPnl(
        ParticipantId participantId
    ) const {
        const AccountPnlState* account =
            findAccount(participantId);

        if (account == nullptr) {
            return 0.0L;
        }

        long double total = 0.0L;

        for (
            const auto& [symbolId, state] :
            account->symbols
        ) {
            auto markIterator =
                mark_prices_.find(symbolId);

            if (
                markIterator ==
                mark_prices_.end()
            ) {
                continue;
            }

            total += calculateUnrealisedPnl(
                state,
                markIterator->second
            );
        }

        return total;
    }

    long double totalPnl(
        ParticipantId participantId
    ) const {
        return realisedPnl(participantId) +
               unrealisedPnl(participantId);
    }

    long double marketValue(
        ParticipantId participantId,
        SymbolId symbolId
    ) const {
        const SymbolPnlState* state =
            findSymbol(
                participantId,
                symbolId
            );

        if (state == nullptr) {
            return 0.0L;
        }

        auto markIterator =
            mark_prices_.find(symbolId);

        if (markIterator == mark_prices_.end()) {
            return 0.0L;
        }

        return
            static_cast<long double>(
                state->position
            ) *
            markIterator->second;
    }

    long double accountEquity(
        ParticipantId participantId
    ) const {
        const AccountPnlState* account =
            findAccount(participantId);

        if (account == nullptr) {
            return 0.0L;
        }

        long double equity =
            account->cash_balance;

        for (
            const auto& [symbolId, state] :
            account->symbols
        ) {
            auto markIterator =
                mark_prices_.find(symbolId);

            /*
                When a mark is missing, value the position at
                its average entry price. This assigns zero
                unrealised P&L rather than treating the
                position as worthless.
            */
            long double valuationPrice =
                state.average_entry_price;

            if (
                markIterator !=
                mark_prices_.end()
            ) {
                valuationPrice =
                    markIterator->second;
            }

            equity +=
                static_cast<long double>(
                    state.position
                ) *
                valuationPrice;
        }

        return equity;
    }

    long double cashBalance(
        ParticipantId participantId
    ) const {
        const AccountPnlState* account =
            findAccount(participantId);

        if (account == nullptr) {
            return 0.0L;
        }

        return account->cash_balance;
    }

    Position position(
        ParticipantId participantId,
        SymbolId symbolId
    ) const {
        const SymbolPnlState* state =
            findSymbol(
                participantId,
                symbolId
            );

        if (state == nullptr) {
            return 0;
        }

        return state->position;
    }

    long double averageEntryPrice(
        ParticipantId participantId,
        SymbolId symbolId
    ) const {
        const SymbolPnlState* state =
            findSymbol(
                participantId,
                symbolId
            );

        if (state == nullptr) {
            return 0.0L;
        }

        return state->average_entry_price;
    }

    void setSymbolName(
        SymbolId symbolId,
        const std::string& symbolName
    ) {
        symbol_names_[symbolId] =
            symbolName;
    }

    const PnlProcessingStatistics&
    statistics() const {
        return statistics_;
    }

    const std::vector<std::string>&
    processingErrors() const {
        return processing_errors_;
    }

    void reset() {
        accounts_.clear();
        mark_prices_.clear();
        symbol_names_.clear();
        processing_errors_.clear();

        statistics_ = {};
        processed_trade_count_ = 0;
    }

    std::string createSummaryReport(
        const PnlReportConfig& config = {}
    ) const {
        if (config.monetary_scale <= 0.0L) {
            throw std::invalid_argument(
                "Report monetary scale must be positive"
            );
        }

        std::ostringstream output;

        output
            << std::fixed
            << std::setprecision(
                config.decimal_places
            );

        output
            << "P&L SUMMARY REPORT\n"
            << "==================\n";

        output
            << "Trades processed: "
            << statistics_.trades_processed
            << '\n';

        output
            << "Rejected trades: "
            << statistics_.trades_rejected
            << '\n';

        output
            << "Participant fills applied: "
            << statistics_
                .participant_fills_applied
            << "\n\n";

        if (accounts_.empty()) {
            output << "No participant accounts.\n";
            return output.str();
        }

        for (
            const auto& [participantId, account] :
            accounts_
        ) {
            long double accountRealised =
                realisedPnl(participantId);

            long double accountUnrealised =
                unrealisedPnl(participantId);

            long double accountTotal =
                accountRealised +
                accountUnrealised;

            long double equity =
                accountEquity(participantId);

            output
                << "Participant "
                << participantId
                << '\n';

            output
                << "-----------"
                << std::string(
                    std::to_string(
                        participantId
                    ).size(),
                    '-'
                )
                << '\n';

            output
                << "Initial cash: "
                << formatMoney(
                    account.initial_cash,
                    config
                )
                << '\n';

            output
                << "Cash balance: "
                << formatMoney(
                    account.cash_balance,
                    config
                )
                << '\n';

            output
                << "Account equity: "
                << formatMoney(
                    equity,
                    config
                )
                << '\n';

            output
                << "Realised P&L: "
                << formatMoney(
                    accountRealised,
                    config
                )
                << '\n';

            output
                << "Unrealised P&L: "
                << formatMoney(
                    accountUnrealised,
                    config
                )
                << '\n';

            output
                << "Total P&L: "
                << formatMoney(
                    accountTotal,
                    config
                )
                << "\n\n";

            for (
                const auto& [symbolId, state] :
                account.symbols
            ) {
                std::string displayName =
                    symbolDisplayName(symbolId);

                auto markIterator =
                    mark_prices_.find(symbolId);

                bool hasMark =
                    markIterator !=
                    mark_prices_.end();

                long double mark =
                    hasMark
                        ? markIterator->second
                        : 0.0L;

                long double unrealised =
                    hasMark
                        ? calculateUnrealisedPnl(
                            state,
                            mark
                        )
                        : 0.0L;

                long double total =
                    state.realised_pnl +
                    unrealised;

                long double symbolMarketValue =
                    hasMark
                        ? static_cast<long double>(
                              state.position
                          ) *
                          mark
                        : 0.0L;

                output
                    << "  Symbol: "
                    << displayName
                    << " ("
                    << symbolId
                    << ")\n";

                output
                    << "    Position: "
                    << state.position
                    << '\n';

                output
                    << "    Average entry: "
                    << formatMoney(
                        state.average_entry_price,
                        config
                    )
                    << '\n';

                output
                    << "    Mark price: ";

                if (hasMark) {
                    output
                        << formatMoney(
                            mark,
                            config
                        );
                } else {
                    output << "N/A";
                }

                output << '\n';

                output
                    << "    Market value: "
                    << formatMoney(
                        symbolMarketValue,
                        config
                    )
                    << '\n';

                output
                    << "    Bought quantity: "
                    << state.bought_quantity
                    << '\n';

                output
                    << "    Sold quantity: "
                    << state.sold_quantity
                    << '\n';

                output
                    << "    Buy notional: "
                    << formatMoney(
                        state.gross_buy_notional,
                        config
                    )
                    << '\n';

                output
                    << "    Sell notional: "
                    << formatMoney(
                        state.gross_sell_notional,
                        config
                    )
                    << '\n';

                output
                    << "    Realised P&L: "
                    << formatMoney(
                        state.realised_pnl,
                        config
                    )
                    << '\n';

                output
                    << "    Unrealised P&L: "
                    << formatMoney(
                        unrealised,
                        config
                    )
                    << '\n';

                output
                    << "    Total P&L: "
                    << formatMoney(
                        total,
                        config
                    )
                    << '\n';

                output
                    << "    Fills: "
                    << state.fill_count
                    << "\n\n";
            }
        }

        return output.str();
    }

private:
    AccountPnlState& ensureAccount(
        ParticipantId participantId
    ) {
        auto [iterator, inserted] =
            accounts_.try_emplace(
                participantId,
                AccountPnlState{
                    participantId,
                    0.0L,
                    0.0L,
                    {}
                }
            );

        static_cast<void>(inserted);

        return iterator->second;
    }

    void applyFill(
        ParticipantId participantId,
        SymbolId symbolId,
        Side side,
        Price price,
        Quantity quantity
    ) {
        AccountPnlState& account =
            ensureAccount(participantId);

        SymbolPnlState& symbol =
            account.symbols[symbolId];

        symbol.symbol_id = symbolId;

        long double tradePrice =
            static_cast<long double>(price);

        long double tradeQuantity =
            static_cast<long double>(quantity);

        long double tradeNotional =
            tradePrice *
            tradeQuantity;

        Position signedQuantity =
            static_cast<Position>(quantity);

        if (side == Side::Buy) {
            account.cash_balance -=
                tradeNotional;

            symbol.net_cash_flow -=
                tradeNotional;

            symbol.bought_quantity +=
                quantity;

            symbol.gross_buy_notional +=
                tradeNotional;
        } else {
            signedQuantity =
                -signedQuantity;

            account.cash_balance +=
                tradeNotional;

            symbol.net_cash_flow +=
                tradeNotional;

            symbol.sold_quantity +=
                quantity;

            symbol.gross_sell_notional +=
                tradeNotional;
        }

        updateAverageCostPosition(
            symbol,
            signedQuantity,
            tradePrice
        );

        ++symbol.fill_count;
    }

    static void updateAverageCostPosition(
        SymbolPnlState& state,
        Position signedTradeQuantity,
        long double tradePrice
    ) {
        Position previousPosition =
            state.position;

        if (previousPosition == 0) {
            state.position =
                signedTradeQuantity;

            state.average_entry_price =
                tradePrice;

            return;
        }

        bool sameDirection =
            (
                previousPosition > 0 &&
                signedTradeQuantity > 0
            ) ||
            (
                previousPosition < 0 &&
                signedTradeQuantity < 0
            );

        if (sameDirection) {
            long double previousQuantity =
                absolutePosition(
                    previousPosition
                );

            long double additionalQuantity =
                absolutePosition(
                    signedTradeQuantity
                );

            Position newPosition =
                previousPosition +
                signedTradeQuantity;

            long double newAbsoluteQuantity =
                absolutePosition(newPosition);

            state.average_entry_price =
                (
                    previousQuantity *
                        state.average_entry_price +
                    additionalQuantity *
                        tradePrice
                ) /
                newAbsoluteQuantity;

            state.position = newPosition;
            return;
        }

        /*
            The trade is closing some or all of the
            existing position.
        */
        long double closingQuantity =
            std::min(
                absolutePosition(previousPosition),
                absolutePosition(
                    signedTradeQuantity
                )
            );

        if (previousPosition > 0) {
            /*
                Closing a long position by selling.
            */
            state.realised_pnl +=
                (
                    tradePrice -
                    state.average_entry_price
                ) *
                closingQuantity;
        } else {
            /*
                Closing a short position by buying.
            */
            state.realised_pnl +=
                (
                    state.average_entry_price -
                    tradePrice
                ) *
                closingQuantity;
        }

        Position newPosition =
            previousPosition +
            signedTradeQuantity;

        if (newPosition == 0) {
            state.position = 0;
            state.average_entry_price = 0.0L;
            return;
        }

        bool retainedOriginalDirection =
            (
                previousPosition > 0 &&
                newPosition > 0
            ) ||
            (
                previousPosition < 0 &&
                newPosition < 0
            );

        if (retainedOriginalDirection) {
            /*
                Partial close. The remaining position keeps
                its original average entry price.
            */
            state.position = newPosition;
            return;
        }

        /*
            The trade was larger than the existing position,
            so the account flipped from long to short or
            short to long.

            The leftover position was opened at this trade's
            price.
        */
        state.position = newPosition;
        state.average_entry_price =
            tradePrice;
    }

    static long double calculateUnrealisedPnl(
        const SymbolPnlState& state,
        long double markPrice
    ) {
        if (state.position > 0) {
            return
                (
                    markPrice -
                    state.average_entry_price
                ) *
                static_cast<long double>(
                    state.position
                );
        }

        if (state.position < 0) {
            return
                (
                    state.average_entry_price -
                    markPrice
                ) *
                absolutePosition(
                    state.position
                );
        }

        return 0.0L;
    }

    static long double absolutePosition(
        Position position
    ) {
        if (position >= 0) {
            return static_cast<long double>(
                position
            );
        }

        return -static_cast<long double>(
            position
        );
    }

    static std::string formatMoney(
        long double rawValue,
        const PnlReportConfig& config
    ) {
        std::ostringstream output;

        output
            << std::fixed
            << std::setprecision(
                config.decimal_places
            );

        output
            << config.currency_prefix
            << (
                rawValue /
                config.monetary_scale
            );

        return output.str();
    }

    std::string symbolDisplayName(
        SymbolId symbolId
    ) const {
        auto iterator =
            symbol_names_.find(symbolId);

        if (
            iterator ==
            symbol_names_.end()
        ) {
            return "SYMBOL_" +
                   std::to_string(symbolId);
        }

        return iterator->second;
    }

    std::map<
        ParticipantId,
        AccountPnlState
    > accounts_;

    std::map<
        SymbolId,
        long double
    > mark_prices_;

    std::map<
        SymbolId,
        std::string
    > symbol_names_;

    std::size_t processed_trade_count_{0};

    PnlProcessingStatistics statistics_;

    std::vector<std::string>
        processing_errors_;
};